// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: cryptobridge.proto

package cryptobridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderBookSnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Market   string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	MaxDepth string `protobuf:"bytes,3,opt,name=maxDepth,proto3" json:"maxDepth,omitempty"`
}

func (x *GetOrderBookSnapshotRequest) Reset() {
	*x = GetOrderBookSnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptobridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderBookSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookSnapshotRequest) ProtoMessage() {}

func (x *GetOrderBookSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptobridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_cryptobridge_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderBookSnapshotRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetOrderBookSnapshotRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetOrderBookSnapshotRequest) GetMaxDepth() string {
	if x != nil {
		return x.MaxDepth
	}
	return ""
}

type GetOrderBookSnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bids []*OrderBookLevel `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks []*OrderBookLevel `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
}

func (x *GetOrderBookSnapshotResponse) Reset() {
	*x = GetOrderBookSnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptobridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderBookSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookSnapshotResponse) ProtoMessage() {}

func (x *GetOrderBookSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptobridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_cryptobridge_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderBookSnapshotResponse) GetBids() []*OrderBookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookSnapshotResponse) GetAsks() []*OrderBookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type OrderBookLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty   string `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *OrderBookLevel) Reset() {
	*x = OrderBookLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptobridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderBookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookLevel) ProtoMessage() {}

func (x *OrderBookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_cryptobridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookLevel.ProtoReflect.Descriptor instead.
func (*OrderBookLevel) Descriptor() ([]byte, []int) {
	return file_cryptobridge_proto_rawDescGZIP(), []int{2}
}

func (x *OrderBookLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderBookLevel) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

var File_cryptobridge_proto protoreflect.FileDescriptor

var file_cryptobridge_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x22, 0x6d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f,
	0x6f, 0x6b, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x22, 0x82, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f,
	0x6f, 0x6b, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x74, 0x79,
	0x32, 0x84, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x29,
	0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cryptobridge_proto_rawDescOnce sync.Once
	file_cryptobridge_proto_rawDescData = file_cryptobridge_proto_rawDesc
)

func file_cryptobridge_proto_rawDescGZIP() []byte {
	file_cryptobridge_proto_rawDescOnce.Do(func() {
		file_cryptobridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_cryptobridge_proto_rawDescData)
	})
	return file_cryptobridge_proto_rawDescData
}

var file_cryptobridge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cryptobridge_proto_goTypes = []interface{}{
	(*GetOrderBookSnapshotRequest)(nil),  // 0: CryptoBridge.GetOrderBookSnapshotRequest
	(*GetOrderBookSnapshotResponse)(nil), // 1: CryptoBridge.GetOrderBookSnapshotResponse
	(*OrderBookLevel)(nil),               // 2: CryptoBridge.OrderBookLevel
}
var file_cryptobridge_proto_depIdxs = []int32{
	2, // 0: CryptoBridge.GetOrderBookSnapshotResponse.bids:type_name -> CryptoBridge.OrderBookLevel
	2, // 1: CryptoBridge.GetOrderBookSnapshotResponse.asks:type_name -> CryptoBridge.OrderBookLevel
	0, // 2: CryptoBridge.MarketDataService.GetOrderBookSnapshot:input_type -> CryptoBridge.GetOrderBookSnapshotRequest
	1, // 3: CryptoBridge.MarketDataService.GetOrderBookSnapshot:output_type -> CryptoBridge.GetOrderBookSnapshotResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cryptobridge_proto_init() }
func file_cryptobridge_proto_init() {
	if File_cryptobridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cryptobridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderBookSnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptobridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderBookSnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptobridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderBookLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cryptobridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptobridge_proto_goTypes,
		DependencyIndexes: file_cryptobridge_proto_depIdxs,
		MessageInfos:      file_cryptobridge_proto_msgTypes,
	}.Build()
	File_cryptobridge_proto = out.File
	file_cryptobridge_proto_rawDesc = nil
	file_cryptobridge_proto_goTypes = nil
	file_cryptobridge_proto_depIdxs = nil
}
